### ISSUE TITLE
 Checkout explanation?

### ISSUE THREAD

**Issue by osseonews** [commercelayer/contentful-gatsby-demo#7]
This is a fantastic demo and looks very promising. I have 2 basic questions:

1. How exactly is the checkout feature implemented? You mention that you use "our open source checkout application". I clicked thru to that application and there is apparently another setup required for that application. Where is this setup in this sample store? Just putting #shopping-bag-checkout - redirects to a checkout? Where is it redirecting to? How is the information sent?

2. What is the {marketId} in the ClayerConfig. Where does this come from? I don't see it reference anywhere, so where does the application get this value?

**Comment by fconforti** [comment]
Hello, thanks for your feedback! To your questions:

1. This is the checkout application that we use in the demo: https://github.com/commercelayer/commercelayer-checkout — The information is taken from the sample Commerce Layer account linked to the demo. If you want, you can create your own account, which is free (forever) in test mode.

2. The market number is taken from the same account.

Hope this helps.

**Comment by osseonews** [comment]
Thanks. Sure, I understand you used the commercelayer-checkout - but how is that implemented in the application? We've already created an account with Commerce Layer. How does the checkout get implemented? Where is it linked from? Where is it imported into the code? Does the ClayerConfig simply call everything in and the checkout functions automatically? With regards to the "market number". Same thing. Where is this set in the application? How is the application pulling this in from the commerce layer account?

**Comment by osseonews** [comment]
OK, I think we figured this out. Didn't realize where the setting were in the Commerce Layer admin panel. It's all the way down at the bottom in the Scope area.
